package com.example.android.insightnews.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFF3C3C)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFF5A489B)
val md_theme_dark_onSecondary = Color(0xFFFFFFFF)
val md_theme_dark_onSecondaryContainer = Color(0xFFBCBCBC)
val md_theme_dark_onTertiaryContainer = Color(0xFF77797D)
val md_theme_dark_background = Color(0xFF11121C)
val md_theme_dark_onBackground = Color(0xFFFAFAFA)
val md_theme_dark_surface = Color(0xFF11121C)
val md_theme_dark_onSurface = Color(0xFFFAFAFA)
val md_theme_dark_surfaceVariant = Color(0x3D767680)
val md_theme_dark_onSurfaceVariant = Color(0xFFFAFAFA)
val md_theme_dark_error = Color(0xFFFA4856)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_outline = Color(0xFFAEB2B9)
val md_theme_dark_outlineVariant = Color(0xFF242424)
val md_theme_dark_scrim = Color(0xFFAEB2B9)

val md_theme_light_primary = Color(0xFFFF3C3C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFF5A489B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF5F646C)
val md_theme_light_onTertiaryContainer = Color(0xFFA3A7AE)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF252729)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF252729)
val md_theme_light_surfaceVariant = Color(0x1F767680)
val md_theme_light_onSurfaceVariant = Color(0xFF252729)
val md_theme_light_error = Color(0xFFFA4856)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_outline = Color(0xFFC6C6C8)
val md_theme_light_outlineVariant = Color(0x66DBDBDB)
val md_theme_light_scrim = Color(0xFFAEB2B9)