package com.github.artnehay.insightnews.core.ui.util

import com.github.artnehay.insightnews.core.ui.R

val SourceToFaviconMap = mapOf(
    "abc-news" to R.drawable.abc_news_favicon_2021,
    "ars-technica" to R.drawable.ars_technica_favicon_2016,
    "associated-press" to R.drawable.associated_press_favicon_2012,
    "bleacher-report" to R.drawable.bleacher_report_favicon_2018,
    "bloomberg" to R.drawable.bloomberg_favicon_2015,
    "business-insider" to R.drawable.business_insider_favicon,
    "cbs-news" to R.drawable.cbs_news_favicon_2020,
    "abc-news" to R.drawable.abc_news_favicon_2021,
    "cnn" to R.drawable.cnn_favicon_2014,
    "engadget" to R.drawable.engadget_favicon_2012,
    "entertainment-weekly" to R.drawable.entertainment_weekly_favicon,
    "espn" to R.drawable.espn_favicon,
    "fortune" to R.drawable.fortune_magazine_favicon,
    "fox-news" to R.drawable.fox_news_favicon_2021,
    "fox-sports" to R.drawable.fox_sports_favicon_2020,
    "google-news" to R.drawable.google_news_favicon_2019,
    "hacker-news" to R.drawable.hacker_news_favicon_2015,
    "ign" to R.drawable.ign_favicon_2012,
    "mashable" to R.drawable.mashable_favicon,
    "msnbc" to R.drawable.msnbc_favicon_2015,
    "mtv-news" to R.drawable.mtv_news_favicon,
    "national-geographic" to R.drawable.national_geographic_favicon,
    "national-review" to R.drawable.national_review_favicon,
    "nbc-news" to R.drawable.nbc_news_2023,
    "new-scientist" to R.drawable.new_scientist_favicon,
    "newsweek" to R.drawable.newsweek_favicon,
    "new-york-magazine" to R.drawable.new_york_magazine_favicon_2015,
    "nfl-news" to R.drawable.nfl_news_favicon_2008,
    "nhl-news" to R.drawable.nhl_news_favicon,
    "politico" to R.drawable.politico_favicon_2016,
    "recode" to R.drawable.recode_favicon_2016,
    "reddit-r-all" to R.drawable.reddit_favicon,
    "reuters" to R.drawable.reuters_favicon_2019,
    "techcrunch" to R.drawable.techcrunch_favicon_2017,
    "techradar" to R.drawable.techradar_favicon_2021,
    "the-huffington-post" to R.drawable.the_huffington_post_favicon_2017,
    "the-next-web" to R.drawable.the_next_web_favicon_2022,
    "the-verge" to R.drawable.the_verge_favicon_2022,
    "the-wall-street-journal" to R.drawable.the_wall_street_journal_favicon_2010,
    "the-washington-post" to R.drawable.the_washington_post_favicon_2013,
    "the-washington-times" to R.drawable.the_washington_times_favicon,
    "time" to R.drawable.time_favicon,
    "usa-today" to R.drawable.usa_today_favicon,
    "vice-news" to R.drawable.vice_news_favicon_2023,
    "wired" to R.drawable.wired_favicon,
)