package com.github.artnehay.insightnews.core.network.util

internal const val Sources =
    "associated-press," +
    "bleacher-report," +
    "bloomberg," +
    "business-insider," +
    "cbs-news," +
    "abc-news," +
    "cnn," +
    "engadget," +
    "entertainment-weekly," +
    "espn," +
    "fortune," +
    "fox-news," +
    "fox-sports," +
    "google-news," +
    "hacker-news," +
    "ign," +
    "mashable," +
    "msnbc," +
    "mtv-news," +
    "national-geographic," +
    "national-review," +
    "nbc-news," +
    "new-scientist," +
    "newsweek," +
    "new-york-magazine," +
    "nfl-news," +
    "nhl-news," +
    "politico," +
    "recode," +
    "reddit-r-all," +
    "reuters," +
    "techcrunch," +
    "techradar," +
    "the-huffington-post," +
    "the-next-web," +
    "the-verge," +
    "the-wall-street-journal," +
    "the-washington-post," +
    "the-washington-times," +
    "time," +
    "usa-today," +
    "vice-news," +
    "wired,"