name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get local.properties from secrets
        env:        
          APIKEY: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          sed "s|APIKEY|$APIKEY|g;" local.defaults.properties > local.properties

